services:
  - type: web
    name: stock-forecast-backend
    env: python
    plan: free
    buildCommand: pip install -r stock_forecast_app/requirements.txt
    startCommand: streamlit run stock_forecast_app/app.py --server.port $PORT --server.address 0.0.0.0

